codegen-haskell: Fix missing include to protobuf-src
Error was:
sh -c 'for pb in monocle/config.proto monocle/search.proto monocle/task_data.proto; do compile-proto-file --includeDir /usr/include --includeDir protos/ --proto ${pb} --out haskell/src/; done'
Error: while processing include statements in "monocle/search.proto", failed
to find the imported file "google/protobuf/timestamp.proto", after looking in the following
locations (controlled via the --includeDir switch(es)):

  /usr/include/google/protobuf/timestamp.proto
  protos/google/protobuf/timestamp.proto