[protobuf] Remove the monocle.messages python module
This change moves the pb2 file to the root monocle monocle so that
cross message import works as expected, instead of failing with:

    File "monocle/messages/search_pb2.py", line 16, in <module>
      from monocle import task_data_pb2 as monocle_dot_task__data__pb2
    ImportError: cannot import name 'task_data_pb2' from 'monocle'